import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card";
import CardContainer from "../components/CardContainer";

const Home: NextPage = () => {
  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <CardContainer>
          <Card />
        </CardContainer>
      </main>
    </div>
  );
};

export default Home;
